name: Deploy Next.js app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          chace: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build Next.js app
        run: pnpm build
        env:
          URL_PREFIX: mol-cal

      - name: Export Next.js app
        run: pnpm export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out